---
title: "NARDINI Plots"
author: "Greg Bedwell"
date: '2022-07-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(tidyverse)
```

```{r}
mat <- as.matrix(data.table::fread("/Users/gbedwell/Documents/github/cider/seq1_nardini_output.txt", header=FALSE))
colnames(mat) <- paste0("x",seq(1,ncol(mat)))
rownames(mat) <- paste0("x",seq(1,nrow(mat)))

mat[lower.tri(mat)] <- NA
```

```{r}
df <- mat %>%
  as.data.frame() %>%
  rownames_to_column("dim1") %>%
  pivot_longer(-c(dim1), names_to = "dim2", values_to = "zscore")

df$dim1 <- factor(df$dim1, levels=rev(sort(unique(df$dim1))))

diag <- df$dim1 == df$dim2
```

```{r}
plot <- ggplot(df, aes(x=dim2, y=dim1, fill=zscore)) +
  geom_tile(color = "black", size = 0.5) +
  geom_tile(data = df[is.na(df$zscore), ], aes(x=dim2, y=dim1, fill=zscore), color = "gray85", size = 0.5) +
  geom_tile(data = df[diag==TRUE,], aes(x=dim2, y=dim1, fill=zscore), color = "black", size = 0.5) +
  geom_text(data = df %>% dplyr::filter(zscore != 0),
            aes(label=round(zscore, 3)),
            size = 4) +
  scale_fill_gradient2(low = "blue",
                       mid = "white",
                       high = "red",
                       midpoint = 0,
                       na.value = "gray85",
                       name = "z-score",
                       limits = c(floor(min(df$zscore)), ceiling(max(df$zscore))),
                       guide = guide_colorbar(frame.colour = "black",
                                              frame.linewidth = 1,
                                              ticks.colour = "black",
                                              ticks.linewidth = 1,
                                              barwidth = 1,
                                              barheight = 21.8,
                                              title.position = "top")) +
  theme_bw() +
  theme(panel.border = element_rect(colour="black", size=1),
        axis.title = element_blank(),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12)) +
  scale_x_discrete(expand = c(0, 0),
                   labels = c("\u03bc","h","+","-","\u03c0","A","P","G")) + 
  scale_y_discrete(expand = c(0, 0),
                   labels = rev(c("\u03bc","h","+","-","\u03c0","A","P","G")))
```

```{r}
ggsave(filename = "test_plot_single.tiff",
       plot = last_plot(),
       device = "tiff",
       width = 6,
       height = 5,
       units = "in")
```

```{r}
file.list <- file.info(list.files(getwd(), full.names = T))
latest.file <- rownames(file.list)[which.max(file.list$mtime)]

```
























